import { Footer } from './_components/Footer/Footer'
import { Header } from './_components/Header/Header'
import './globals.css'
import { Roboto } from 'next/font/google'
import { StoreProvider } from './redux/StoreProvider'

const roboto = Roboto({
    weight: ['300', '400', '700'],
    subsets: ['latin']
})

export const metadata = {
    title: 'Tickets Search',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru">
        <body className={`${roboto.className}`}>
            <StoreProvider>
                <div className='wrapper'>
                    <Header/>
                        <div className='content'>
                            {children}
                        </div>
                    <Footer/>
                </div>
            </StoreProvider>
        </body>
        </html>
    )
}
